FROM node:22-alpine

WORKDIR /app
COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci
RUN npx prisma generate

EXPOSE 3000
CMD ["sh", "-c", "npx prisma migrate dev && npm run dev"]
